config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, status: :see_other
  end

  private

  # STRONG_PARAMS
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  # STRONG_PARAMS
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
     <%= yield %>
  </div>

  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<% if @lists.empty? %>
<p>No lists yet!</p>
<%= link_to "Create a list", new_list_path %>
<% else %>
  <ul class="list-group">
    <% @lists.each do |list| %>
    <li><%= link_to list.name, list %></li>
    <% end %>
  </ul>
<% end %>

<hr>
<%= link_to "Add a new list", new_list_path %>

app/views/lists/new.html.erb
<h1>Create New List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<hr>
<%= link_to "Back to all lists", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% if @list.movies.empty? %>
<p>No movies yet!</p>
<% else %>
  <ul>
    <% @list.movies.each do |movie| %>
    <li><%= movie.title %></li>
    <% end %>
  </ul>
<% end %>

<h3>Add a Movie</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

<hr>
<%= link_to "Back to all lists", lists_path %>